services:
  dataherald-engine:
    image: dataherald.azurecr.io/dataherald-engine:latest
    container_name: dataherald-engine
    ports:
      - "80:80"
    networks:
      - dataherald_network
    environment:
      - MONGODB_URI=mongodb://dataherald-mongodb:27017
    platform: linux/amd64

  dataherald-mongodb:
    image: mongo:latest
    container_name: dataherald-mongodb
    ports:
      - "27017:27017"
    networks:
      - dataherald_network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_DB_PASSWORD}
    platform: linux/amd64

  dataherald-enterprise:
    image: dataherald.azurecr.io/dataherald-enterprise:latest
    container_name: dataherald-enterprise
    networks:
      - dataherald_network
    ports:
      - "3001:8080"
    platform: linux/amd64

  dataherald-admin-console:
    image: dataherald.azurecr.io/dataherald-admin-console:latest
    container_name: dataherald-admin-console
    ports:
      - "3000:3000"
    networks:
      - dataherald_network
    platform: linux/amd64

networks:
  dataherald_network:
    driver: bridge
